language: c

services:
- docker

env:
  global:
# https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1802718
# and/or travis docker image(s) not having enabled 'deb-src' lines
# contrary to docker documentation -> https://docs.docker.com/samples/library/ubuntu/
# NB At time of writing 2018-11-11: artful doesn't really need this FIX_APT_CONFIG, but no harm in applying it
   - FIX_APT_CONFIG="more /etc/apt/sources.list && sed -i '/^#\sdeb-src /s/^#//' '/etc/apt/sources.list'"
  matrix:
# xenial does not have a new enough geoclue, so simply disable it.
# (rather than trying to bother building this source dependency)
   - BUILD_IMG=ubuntu:xenial DEPS=libmapnik-dev OPTS="--disable-geoclue"
   - BUILD_IMG=ubuntu:artful
   - BUILD_IMG=ubuntu:bionic
   - BUILD_IMG=ubuntu:cosmic
# NB Ubuntu 14.04(ubuntu:trusty) doesn't support building geoclue 2.x because it requires GLib >= 2.44.0 which is hard to install

script: docker run --rm=true -v $HOME:$HOME:rw $BUILD_IMG /bin/sh -c "$FIX_APT_CONFIG && apt-get update && apt-get build-dep --yes viking && apt-get install --yes gtk-doc-tools nettle-dev liboauth-dev libzip-dev $DEPS && cd $PWD && ./autogen.sh $OPTS && make -j && make -j check && make install"
# Further packages are installed as these are new dependencies for the latest source code, compared to the dependencies listed in the distribution version (`apt-get build-dep` always refers to the version which is built for the OS rather than the up-to-date source)
